### PR TITLE
Fixed the MANIFEST

### PR DESCRIPTION
**Pull request by davorg**
Sorry. Forgot this bit :-/

### CODE REVIEW

**Comment by jokergoo** [comment]
Thanks!

**Comment by davorg** [comment]
Hi, any chance you could push this version to CPAN? Thanks.

**Comment by jokergoo** [comment]
Yes, sure! I will do it as soon as possible.

**Comment by jokergoo** [comment]
Hi, it has been updated. http://search.cpan.org/~jokergoo/Statistics-Multtest-0.14/

**Pull request merged**
